name: TGSGK自动签到
 
on: push
  #schedule:
   # - cron: '0 0 * * *' # 每天中午12点执行

jobs:
  run-telethon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'
 
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon
        #pip install requests
        # 安装其他依赖...

    - name: Run Telethon Script
      env:
        TG_API_ID: ${{ secrets.TG_API_ID }}
        TG_API_HASH: ${{ secrets.TG_API_HASH }}
        your-file-path: .github/workflows/chenxu.session
      run: |
        python .github/workflows/tgx.py
