name: TGSGK自动签到

#on: [push]    
#此项开启时为文件有更新立即执行Actions，与下面3行代码有冲突

on: 
 schedule:
    - cron: '0 2 * * *'  # 每天2点执行（github时间）


    
jobs:
  run-telethon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
        #配置python环境...
 
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon
        pip install requests
        # 安装其他依赖...

    - name: Run Telethon Script
      env:
        TG_API_HASH1: ${{ secrets.TG_API_HASH1 }}  #HASH环境变量1
        TG_API_HASH2: ${{ secrets.TG_API_HASH2 }}   #HASH环境变量2
        
        WECHATPUSH_TOKEN: ${{ secrets.WECHATPUSH_TOKEN }}    #微信推送环境变量 https://www.pushplus.plus/
        
        #配置环境变量...
      run: |
        python sign.py
        python wechatpush.py
