name: TGSGK自动签到
on: 
  schedule:
    - cron: '0 2 * * *'  # 每天中午12点执行
jobs:
  run-telethon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'

 
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon
        #pip install requests
        # 安装其他依赖...

    - name: Run Telethon Script
      env:
        TG_API_ID1: ${{ secrets.TG_API_ID1 }}
        TG_API_HASH1: ${{ secrets.TG_API_HASH1 }}
        TG_API_ID2: ${{ secrets.TG_API_ID2 }}
        TG_API_HASH2: ${{ secrets.TG_API_HASH2 }}
       # your-file-path: .github/workflows
       # uses: .github/workflows
       
      run: |
        python .github/workflows/tgx.py
